### ISSUE TITLE
Says extension already installed, but its not.

### ISSUE THREAD

**Issue by aasutossh** [InspectorMustache/maninex#3]
Weird problem.
Tried to install ublock origin, but it says extension already installed.
Then I check **/usr/share/inox/extension**, And I find there are more extension listed than installed.
Also there is ublock's "code" listed `(cjpalhdlnbpafiamejdnhcphjbkeiagm)`.

**Comment by RealFerdinandDeSaussure** [comment]
I don't think I understand completely yet. Could you post the contents of your maninex.conf as well as the output of `ls [json_dir]` and `ls [extension_dir]`?
To be honest, I don't much use this script anymore as I've switched to qutebrowser. So keeping it updated is kind of a low priority for me. That being said, I'll do what I can to help.

**Comment by aasutossh** [comment]
I also love qutebrowser, but I prefer inox than iridium and inox doesn't have native webstore support.
`ls [json_dir]` gives:
ls /usr/share/inox/extensions
`aapbdbdomjkkjkaonfhkkikfgjllcleb.json  gmpljdlgcdkljlppaekciacdmdlhfeon.json`
`abfimpkhacgimamjbiegeoponlepcbob.json  haigaafonckooggfpmjplfpbkafelcfe.json`
`cjpalhdlnbpafiamejdnhcphjbkeiagm.json  hoboanjcaobnfchcnlgjhmnmogmnbipb.json`
`efjgjleilhflffpbnkaofpmdnajdpepi.json  jpfpebmajhhopeonhlcgidhclcccjcik.json`
`fngmhnnpilhplaeedifhccceomclgfbg.json  lgblnfidahcdcjddiepkckcfdhpknnjh.json`
`gagfkmknmijppikpcikmbbkdkhggcmge.json  llaficoajjainaijghjlofdfmbjpebpa.json`
`gcalenpjmijncebpfijmoaglllgpjagf.json  ogfcmafjalglgifnmanfmnieipoejdcf.json`
and `ls [extension_dir]` gives
`aapbdbdomjkkjkaonfhkkikfgjllcleb  gmpljdlgcdkljlppaekciacdmdlhfeon`
`abfimpkhacgimamjbiegeoponlepcbob  haigaafonckooggfpmjplfpbkafelcfe`
`cjpalhdlnbpafiamejdnhcphjbkeiagm  hoboanjcaobnfchcnlgjhmnmogmnbipb`
`efjgjleilhflffpbnkaofpmdnajdpepi  jpfpebmajhhopeonhlcgidhclcccjcik`
`fngmhnnpilhplaeedifhccceomclgfbg  lgblnfidahcdcjddiepkckcfdhpknnjh`
`gagfkmknmijppikpcikmbbkdkhggcmge  llaficoajjainaijghjlofdfmbjpebpa`
`gcalenpjmijncebpfijmoaglllgpjagf  ogfcmafjalglgifnmanfmnieipoejdcf`
and ~/.config/maninex.conf has
`[directories]`
`json_dir = /usr/share/inox/extensions`
`extension_dir = ~/.config/inox/extensions`

`[extensions]`
`Seedr = abfimpkhacgimamjbiegeoponlepcbob`
`Google Translate = aapbdbdomjkkjkaonfhkkikfgjllcleb`
`Docs Online Viewer = gmpljdlgcdkljlppaekciacdmdlhfeon`
`Fair AdBlocker = lgblnfidahcdcjddiepkckcfdhpknnjh`
`dmitlichess = haigaafonckooggfpmjplfpbkafelcfe`
`Speed Dial 2 New tab = jpfpebmajhhopeonhlcgidhclcccjcik`
`uBlock Origin = cjpalhdlnbpafiamejdnhcphjbkeiagm`

I don't have ublock and fair adblocker installed in the browser but running `maninex -i` gives as already installed.
And as you can see the "code" for both are listed in the extension dir and also in json dir.

**Comment by RealFerdinandDeSaussure** [comment]
Well there is a corresponding extension directory and a json file for both those extensions so maninex considers them installed. You can try deleting those directories/files and running install mode again. Or you could post the contents of both those extension json files. My guess would be that there is some kind of interference between extensions which causes those two to not show up as installed in Chromium. Sophisticated checking for installation status other than by simply looking up the existence of the appropriate extension files might get very complicated and I'd also consider it beyond the scope of this "project". Quite possibly it's also beyond the scope of my limited expertise.

**Comment by aasutossh** [comment]
Its fine anyway, I use qutebrowser almost all the time. For chromium purposes I can use iridium browser.
