### ISSUE TITLE
Archlinux packaging

### ISSUE THREAD

**Issue by PaNaVTEC** [InspectorMustache/maninex#4]
Hi, I would really appreciate if you can add an archlinux package in aur. Archlinux users can't install it if we already have some dependencies installed from aur.

Thanks for your project, works like a charm!

**Comment by RealFerdinandDeSaussure** [comment]
I'm actually an Arch user myself, however I've never packaged anything before. I guess this might be a good opportunity to learn more about it that. In the meantime you can use virtualenv for setting up a temporary Python environment in which you can run pip to install maninex.

**Comment by RealFerdinandDeSaussure** [comment]
Alright, I created a package [here](https://aur.archlinux.org/packages/maninex/). Give it a try.

**Comment by PaNaVTEC** [comment]
works like a charm,

maniThanks!
